[target.'cfg(all())']
rustflags = [
    "-Wclippy::fallible_impl_from",
    "-Dclippy::unwrap_used",  # Forbid `unwrap()`
    "-Dclippy::expect_used",  # Forbid `expect()`
    "-Dclippy::panic",  # Forbid `panic!`
    "-Dclippy::print_stdout",  # Forbid `println!` and `print!`
    "-Dclippy::dbg_macro",  # Forbid `dbg!`
    "-Dclippy::todo",  # Forbid `todo!`
    "-Dclippy::unimplemented",  # Forbid `unimplemented!`
    "-Dclippy::style",  # Forbid all style lints
]

[alias]
format = "fmt --all"
format-check = "fmt --all -- --check"
lint = "clippy --all-targets --all-features -- -D warnings"
lint-fix = "clippy --all-targets --all-features --fix --allow-dirty --allow-staged"
coverage = "llvm-cov --no-clean --lcov --output-path coverage.lcov"
