name: tests
on: [push]
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-targets --all-features -- -D warnings

      - run: cargo test

      - run: cargo build --release --all-features
